# Generated by Django 5.2.7 on 2026-01-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_alter_mentorshipsession_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcontribution',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='contributions/images/'),
        ),
    ]
