# Generated by Django 6.0.3 on 2026-03-15 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_contentcontribution_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentcontribution',
            old_name='token_reward',
            new_name='reward_amount',
        ),
        migrations.RenameField(
            model_name='mentorshipsession',
            old_name='token_fee',
            new_name='fee_amount',
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='fee_30min',
            field=models.IntegerField(default=10, help_text='Fee (in Rupee) for 30-minute session', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='fee_60min',
            field=models.IntegerField(default=20, help_text='Fee (in Rupee) for 60-minute session', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
