# Generated by Django 5.2.7 on 2025-10-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='previous_experience',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
