# Generated by Django 5.2.7 on 2025-10-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter 10 digit phone number', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('mentor', 'Mentor'), ('Admin', 'Admin')], default='user', max_length=10),
        ),
    ]
