# Generated by Django 5.2.7 on 2025-10-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_phone_number_mentorshipsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorshipSession',
        ),
    ]
