# Generated by Django 5.2.7 on 2025-11-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_mentorshipsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='available_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='available_from',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='available_to',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(help_text='A brief introduction about yourself.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience_years',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='expertise',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='mentor_videos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profession',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='mentor_photos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='session_duration',
            field=models.CharField(choices=[('30', '30 Minutes'), ('60', '60 Minutes')], max_length=10, null=True),
        ),
    ]
